##
## EPITECH PROJECT, 2021
## makefile
## File description:
## Makefile
##

clean:
	cd antman && make clean
	cd giantman && make clean

fclean: clean
	cd antman && make fclean
	cd giantman && make fclean

re:
	cd antman && make re
	cd giantman && make re